print("from,")
print("\tG.dhivya,")
print("\tSt.Joseph of Cluny.")
print("to,")
print("\tthe principal,")
print("\tSt.Joseph of Cluny,")
print("\tlawspet, pondicherry.")
print("\nSUB: Req for leave.")
print("\ndear sister,")
print("\t with due respect, i want to say that I am not in a position to attend the school as I am down due to fever.I have been recommended by our family doctor to take proper rest for a few days hence i kindly request you to grant me leave from 7.06 22 to 9.06.22.")
print("\t \t \t \t \t \t \t \t \t thanking you.")
print("place: pondicherry \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                yours obediently,")
print("date:07.06.22      \t\t\t\t\t\t\t\t\t\t\t\t\t\t\t                G.Dhivya.")
